step_defs/createbusinesspartner_test.py::py::test_crear_un_business_partner[UITest-Pytest-Test-T3ts]
--------------------------------------------------------------------
Last Page: [WARNING! Browser Not Open!]
  Browser: chrome (107.0.5304.107)
   Driver: chromedriver (106.0.5249.61)
Timestamp: 1669670611  (Unix Timestamp)
     Date: Monday, November 28, 2022
     Time: 5:23:31 PM  (Hora est√°ndar de Venezuela, UTC-04:00)
--------------------------------------------------------------------
Traceback:   File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 174, in scenario_wrapper
    _execute_scenario(feature, scenario, request)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 144, in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 108, in _execute_step_function
    kwargs = {arg: request.getfixturevalue(arg) for arg in get_args(step_func)}
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 108, in <dictcomp>
    kwargs = {arg: request.getfixturevalue(arg) for arg in get_args(step_func)}
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 554, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 573, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 659, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 1057, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 1111, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\fixtures.py", line 890, in call_fixture_func
    fixture_result = fixturefunc(**kwargs)
  File "C:\Users\kaizen\Desktop\pytestbb\AutomatizacionUIBusinessBuilder\UI_test\step_defs\login.py", line 27, in login_con_cookies_usuario_y_contrasena
    sb.execute_script(Login.ButtonFlag)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumbase\fixtures\base_case.py", line 2518, in execute_script
    self.__check_browser()
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumbase\fixtures\base_case.py", line 10571, in __check_browser
    raise NoSuchWindowException("Active window was already closed!")

Exception: Message: Active window was already closed!
