step_defs/createwarehouse_test.py::py::test_crear_un_almacen[UITestP1th0n-Pytest-PyT]
--------------------------------------------------------------------
Last Page: https://test-xweb.eurokaizen.com/Management/Warehouse/Form
  Browser: chrome (101.0.4951.64)
   Driver: chromedriver (101.0.4951.41)
Timestamp: 1652301436  (Unix Timestamp)
     Date: Wednesday, May 11, 2022
     Time: 4:37:16 PM  (Hora estándar de Venezuela, UTC-04:00)
--------------------------------------------------------------------
Traceback:   File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\_pytest\python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 174, in scenario_wrapper
    _execute_scenario(feature, scenario, request)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 138, in _execute_scenario
    step_func = _find_step_function(request, step, scenario)
  File "C:\Users\kaizen\AppData\Local\Programs\Python\Python38\lib\site-packages\pytest_bdd\scenario.py", line 86, in _find_step_function
    raise exceptions.StepDefinitionNotFoundError(

Exception: Step definition is not found: Then "añado el Impuesto Atributos Equipos Contacto Imagen". Line 9 in scenario "Crear un Almacen" in the feature "C:\Users\kaizen\OneDrive\Escritorio\Business building pytest\AutomatizacionUIBusinessBuilder\UI_test\features\createwarehouse.feature"